services:
  backend_service_user:
    container_name: be_service_user
    depends_on:
      - mongo-user
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - ./data/user.csv:/app/data/user.csv
      - /app/node_modules
    ports:
      - "4001:3000"
    environment:
      TZ: Europe/Berlin
      MONGO_URI: mongodb://mongo-user:27017/userdb

  mongo-user:
    container_name: db_user
    image: mongo:6
    ports:
      - "35555:27017"
    volumes:
      - mongo_user_data:/data/db

volumes:
  mongo_user_data:
